name: Generate Snake

on:
  schedule:
      # every day
    - cron: "0 0/12 * * *"
  workflow_dispatch:
  # run on every push on the master branch
  push:
    branches:
    - main
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2.5.0
      - name: Waka - Readme
        # You may pin to the exact commit or the version.
        # uses: athul/waka-readme@1f2d0f1334ec066ef92b9eaf14242cd062bcd254
        uses: athul/waka-readme@v0.1.5
        with:
          # Your Wakatime API Key
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

      - uses: Platane/snk@v2.0.0-rc.2
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          # these next 2 lines generate the files on a branch called "output". This keeps the main branch from cluttering up.
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg
      # show the status of the build. Makes it easier for debugging (if there's any issues).
      - run: git status
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

